#include "gma.h"
#include "extmath.h"
#include "../objparse/objparse.h"

int GCMFSizes[256];

void writeGma()
{
	for(int i=0; i<tallyObjs; i++)
	{
		char tempfn[80];
		sprintf(tempfn,"./temp/temp%d.gma.part",i);
		FILE * temp = fopen(tempfn,"wb");
		//GCMF Header
		putc('G',temp);
		putc('C',temp);
		putc('M',temp);
		putc('F',temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0x43,temp);
		putc(0x80,temp);
		putc(0x00,temp);
		putc(0x00,temp);
		putc(0,temp);
		putc(1,temp);
		putc(0,temp);
		putc(1,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0x60,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		//Texture Info
		putc(0,temp);
		putc(0,temp);
		putc(0x07,temp);
		putc(0x94,temp);
		int mtlId = -1;
		for(int j=0; j<tallyMtls; j++)
		{
			if(strcmp(cmnObjs[i].mat,cmnMtls[j].mtlname)==0) mtlId=j;
		}
		if(mtlId==-1) printf("ERROR! Material name %s doesn't exist!\n",cmnObjs[i].mat);
		putc((mtlId>>8)&0xFF,temp);
		putc(mtlId&0xFF,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0x30,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		//Model Header
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0xFF,temp);
		putc(1,temp);
		putc(3,temp);
		putc(0xFF,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0x26,temp);
		putc(0,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0xFF,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		putc(0,temp);
		//Model Data
		putc(0,temp);
		for(int j=0; j<tallyTris; j++)
		{
			putc(0x98,temp);
			putc(0,temp);
			putc(3,temp);
			int posx = toInt(cmnVertices.vs[cmnObjs[i].tris[j].va].x);
			int posy = toInt(cmnVertices.vs[cmnObjs[i].tris[j].va].y);
			int posz = toInt(cmnVertices.vs[cmnObjs[i].tris[j].va].z);
			int nrmx = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vna].x);
			int nrmy = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vna].y);
			int nrmz = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vna].z);
			int texx = toInt(cmnTexCoords.vts[cmnObjs[i].tris[j].vta].x);
			int texy = toInt(cmnTexCoords.vts[cmnObjs[i].tris[j].vta].y);
			putc((posx>>24)&0xFF,temp);
			putc((posx>>16)&0xFF,temp);
			putc((posx>>8)&0xFF,temp);
			putc(posx&0xFF,temp);
			putc((posy>>24)&0xFF,temp);
			putc((posy>>16)&0xFF,temp);
			putc((posy>>8)&0xFF,temp);
			putc(posy&0xFF,temp);
			putc((posz>>24)&0xFF,temp);
			putc((posz>>16)&0xFF,temp);
			putc((posz>>8)&0xFF,temp);
			putc(posz&0xFF,temp);
			putc((nrmx>>24)&0xFF,temp);
			putc((nrmx>>16)&0xFF,temp);
			putc((nrmx>>8)&0xFF,temp);
			putc(nrmx&0xFF,temp);
			putc((nrmy>>24)&0xFF,temp);
			putc((nrmy>>16)&0xFF,temp);
			putc((nrmy>>8)&0xFF,temp);
			putc(nrmy&0xFF,temp);
			putc((nrmz>>24)&0xFF,temp);
			putc((nrmz>>16)&0xFF,temp);
			putc((nrmz>>8)&0xFF,temp);
			putc(nrmz&0xFF,temp);
			putc((texx>>24)&0xFF,temp);
			putc((texx>>16)&0xFF,temp);
			putc((texx>>8)&0xFF,temp);
			putc(texx&0xFF,temp);
			putc((texy>>24)&0xFF,temp);
			putc((texy>>16)&0xFF,temp);
			putc((texy>>8)&0xFF,temp);
			putc(texy&0xFF,temp);
			posx = toInt(cmnVertices.vs[cmnObjs[i].tris[j].vb].x);
			posy = toInt(cmnVertices.vs[cmnObjs[i].tris[j].vb].y);
			posz = toInt(cmnVertices.vs[cmnObjs[i].tris[j].vb].z);
			nrmx = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vnb].x);
			nrmy = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vnb].y);
			nrmz = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vnb].z);
			texx = toInt(cmnTexCoords.vts[cmnObjs[i].tris[j].vtb].x);
			texy = toInt(cmnTexCoords.vts[cmnObjs[i].tris[j].vtb].y);
			putc((posx>>24)&0xFF,temp);
			putc((posx>>16)&0xFF,temp);
			putc((posx>>8)&0xFF,temp);
			putc(posx&0xFF,temp);
			putc((posy>>24)&0xFF,temp);
			putc((posy>>16)&0xFF,temp);
			putc((posy>>8)&0xFF,temp);
			putc(posy&0xFF,temp);
			putc((posz>>24)&0xFF,temp);
			putc((posz>>16)&0xFF,temp);
			putc((posz>>8)&0xFF,temp);
			putc(posz&0xFF,temp);
			putc((nrmx>>24)&0xFF,temp);
			putc((nrmx>>16)&0xFF,temp);
			putc((nrmx>>8)&0xFF,temp);
			putc(nrmx&0xFF,temp);
			putc((nrmy>>24)&0xFF,temp);
			putc((nrmy>>16)&0xFF,temp);
			putc((nrmy>>8)&0xFF,temp);
			putc(nrmy&0xFF,temp);
			putc((nrmz>>24)&0xFF,temp);
			putc((nrmz>>16)&0xFF,temp);
			putc((nrmz>>8)&0xFF,temp);
			putc(nrmz&0xFF,temp);
			putc((texx>>24)&0xFF,temp);
			putc((texx>>16)&0xFF,temp);
			putc((texx>>8)&0xFF,temp);
			putc(texx&0xFF,temp);
			putc((texy>>24)&0xFF,temp);
			putc((texy>>16)&0xFF,temp);
			putc((texy>>8)&0xFF,temp);
			putc(texy&0xFF,temp);
			posx = toInt(cmnVertices.vs[cmnObjs[i].tris[j].vc].x);
			posy = toInt(cmnVertices.vs[cmnObjs[i].tris[j].vc].y);
			posz = toInt(cmnVertices.vs[cmnObjs[i].tris[j].vc].z);
			nrmx = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vnc].x);
			nrmy = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vnc].y);
			nrmz = toInt(cmnNormals.vns[cmnObjs[i].tris[j].vnc].z);
			texx = toInt(cmnTexCoords.vts[cmnObjs[i].tris[j].vtc].x);
			texy = toInt(cmnTexCoords.vts[cmnObjs[i].tris[j].vtc].y);
			putc((posx>>24)&0xFF,temp);
			putc((posx>>16)&0xFF,temp);
			putc((posx>>8)&0xFF,temp);
			putc(posx&0xFF,temp);
			putc((posy>>24)&0xFF,temp);
			putc((posy>>16)&0xFF,temp);
			putc((posy>>8)&0xFF,temp);
			putc(posy&0xFF,temp);
			putc((posz>>24)&0xFF,temp);
			putc((posz>>16)&0xFF,temp);
			putc((posz>>8)&0xFF,temp);
			putc(posz&0xFF,temp);
			putc((nrmx>>24)&0xFF,temp);
			putc((nrmx>>16)&0xFF,temp);
			putc((nrmx>>8)&0xFF,temp);
			putc(nrmx&0xFF,temp);
			putc((nrmy>>24)&0xFF,temp);
			putc((nrmy>>16)&0xFF,temp);
			putc((nrmy>>8)&0xFF,temp);
			putc(nrmy&0xFF,temp);
			putc((nrmz>>24)&0xFF,temp);
			putc((nrmz>>16)&0xFF,temp);
			putc((nrmz>>8)&0xFF,temp);
			putc(nrmz&0xFF,temp);
			putc((texx>>24)&0xFF,temp);
			putc((texx>>16)&0xFF,temp);
			putc((texx>>8)&0xFF,temp);
			putc(texx&0xFF,temp);
			putc((texy>>24)&0xFF,temp);
			putc((texy>>16)&0xFF,temp);
			putc((texy>>8)&0xFF,temp);
			putc(texy&0xFF,temp);
		}
		int size = ftell(temp);
		int paddingSize = 16-(size%16);
		for(int j=0; j<paddingSize; j++) putc(0,temp);
		GCMFSizes[i] = ftell(temp);
		fclose(temp);
	}
	FILE * gma = fopen("./temp/output.gma","wb");
	putc((tallyObjs>>24)&0xFF,gma);
	putc((tallyObjs>>16)&0xFF,gma);
	putc((tallyObjs>>8)&0xFF,gma);
	putc(tallyObjs&0xFF,gma);
	putc(((8+tallyObjs*16)>>24)&0xFF,gma);
	putc(((8+tallyObjs*16)>>16)&0xFF,gma);
	putc(((8+tallyObjs*16)>>8)&0xFF,gma);
	putc((8+tallyObjs*16)&0xFF,gma);
	for(int i=0; i<tallyObjs; i++)
	{
		int modelOffset = 0;
		if(i!=0)
		{
			for(int j=0; j<i-1; j++)
			{
				modelOffset += GCMFSizes[j];
			}
		}
		putc((modelOffset>>24)&0xFF,gma);
		putc((modelOffset>>16)&0xFF,gma);
		putc((modelOffset>>8)&0xFF,gma);
		putc(modelOffset&0xFF,gma);
		putc(((i*8)>>24)&0xFF,gma);
		putc(((i*8)>>16)&0xFF,gma);
		putc(((i*8)>>8)&0xFF,gma);
		putc((i*8)&0xFF,gma);
	}
	for(int i=0; i<tallyObjs; i++)
	{
		char name[40];
		sprintf(name,"%04X",i);
		putc(name[0],gma);
		putc(name[1],gma);
		putc(name[2],gma);
		putc(name[3],gma);
		putc(0,gma);
		putc(0,gma);
		putc(0,gma);
		putc(0,gma);
	}
	for(int i=0; i<tallyObjs; i++)
	{
		char tempfn[80];
		sprintf(tempfn,"./temp/temp%d.gma.part",i);
		FILE * temp = fopen(tempfn,"rb");
		for(int j=0; j<GCMFSizes[i]; j++) putc(getc(temp),gma);
		fclose(temp);
	}
	fclose(gma);
}
